Add StatsCollector to Client
fauna/fauna-dotnet pull request #132
Opened 2024-07-05 11:14 UTC by cynicaljoy

## Problem

Uses need a way to retrieve the query stats that are returned for both standard queries and when using Pagination

## Change

- Add a `StatsCollector` to the `Client`

2024-07-05 12:04 UTC, pnwpedro requested changes

2024-07-05 12:04 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +    internal void Sum(QueryStats stats)
```suggestion
    internal void Add(QueryStats stats)
```

2024-07-05 12:11 UTC, pnwpedro commented on Fauna/Client/Client.cs
>                  throw ExceptionFactory.FromQueryFailure(ctx, failure);
Oh, and we get stats on failures as well.

2024-07-05 15:53 UTC, freels reviewed
Looks like we're going in the right direction here. 

One more comment in addition to the below: 

While a simple lock is going to be sufficient for most applications, for higher performance ones it could be a source of contention if the client is shared across many threads.

If you're up for it, take a look at some of the concurrency primitives C# provides. This class looks promising: https://learn.microsoft.com/en-us/dotnet/api/system.threading.interlocked?view=net-8.0

That being said I'm fine if we go for a lock-based impl for now.

2024-07-05 15:53 UTC, freels commented on Fauna/Client/StatsCollector.cs
> +    public QueryStats Read()
This is correct. You need 'ReadAndReset()` to be a single atomic action or else you can miss stats between the two calls. 

So I'd like to see two methods: `Read()` and `ReadAndReset()` (no need for a separate `Reset()` method, it'd just be ripe for abuse.)

Using `Get` vs `Read` as a verb I don't have a pref but think it should be the same one.

2024-07-05 15:53 UTC, freels commented on Fauna/Client/StatsCollector.cs
> +                RateLimitsHit = MergeLists(Stats.RateLimitsHit, stats.RateLimitsHit),
+1 for a map

2024-07-05 15:53 UTC, freels commented on Fauna/Client/StatsCollector.cs
> +            Stats = new QueryStats
Agree, it would be more memory efficient to mutate rather than copy.

I'd keep QueryStats `readonly` since that will prevent users from accidentally mutating it (would be bad if we hand them a shared one!). 

I'd make the individual running stats private fields on StatsCollector that you can mutate under the lock.

2024-07-05 22:26 UTC, cynicaljoy commented on Fauna/Client/StatsCollector.cs
> +        try
```
  Failed UnauthorizedException_Basic [94 ms]
  Error Message:
     Expected: <Fauna.Exceptions.UnauthorizedException>
  But was:  <System.NullReferenceException: Object reference not set to an instance of an object.
   at Fauna.QueryStats.ToDictionary() in /home/runner/work/fauna-dotnet/fauna-dotnet/Fauna/Response/QueryStats.cs:line 25
   at Fauna.StatsCollector.Add(QueryStats stats) in /home/runner/work/fauna-dotnet/fauna-dotnet/Fauna/Client/StatsCollector.cs:line 35
   at Fauna.Client.QueryAsyncInternal[T](Query query, IDeserializer`1 deserializer, MappingContext ctx, QueryOptions queryOptions, CancellationToken cancel) in /home/runner/work/fauna-dotnet/fauna-dotnet/Fauna/Client/Client.cs:line 123
   at Fauna.Test.Exceptions.ServiceExceptionTests.<>c__DisplayClass8_0.<<UnauthorizedException_Basic>b__0>d.MoveNext() in /home/runner/work/fauna-dotnet/fauna-dotnet/Fauna.Test/Exceptions/ServiceException.Tests.cs:line 85
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args)>

  Stack Trace:
     at Fauna.Test.Exceptions.ServiceExceptionTests.UnauthorizedException_Basic() in /home/runner/work/fauna-dotnet/fauna-dotnet/Fauna.Test/Exceptions/ServiceException.Tests.cs:line 85

```

options:

1. live with `try` 
2. update stats to be nullable 
3. update core to return empty stats on unauthorized

2024-07-08 10:58 UTC, pnwpedro requested changes
Nice! Moving in the right direction.

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +        try
Since QueryStats is a struct, it will never be null when uninitialized. Instead it's default of that struct. The default struct will be an instance with all of the fields set to their default values. So if you're getting a null ref, it's because you're interacting with a field whose type defaults to null without checking it.

The answer here should be to handle that directly in your dictionary `RateLimitsHit?.Count ?? 0`

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Response/QueryStats.cs
> +    }
```suggestion
```

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +public class StatsCollector
Let's make an interface for this since we're allowing users to inject it. That will give them the freedom to something a little different for each query instead of aggregating if they choose (e.g. a stats sink of some kind).

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Response/QueryStats.cs
> +            { StatsKey.RateLimitsHit, RateLimitsHit.Count }
We don't want just a number here. If it's not null/empty, we need to handle each present key and increment some field by 1, directly on the StatsCollector I think.

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +            var statsDict = stats.ToDictionary();
If the dict is just to iterate through the properties, try `typeof(QueryStats).GetProperties`. We can optimize it later if we don't like the performance.

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +        private set => Interlocked.Exchange(ref _statsArray[(int)key], value);
Clever, but unfortunately this assumes an enum implementation. If someone decides to add a special StatsKey in the future and assigns it an arbitrary number, this will break at runtime. Probably individual stat fields would be straight forward and failsafe.

2024-07-08 10:58 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +        var statsDict = new Dictionary<StatsKey, int>();
I don't like the idea of returning a dictionary because they aren't terribly friendly, and we shouldn't be returning just ints given we'll have fidelity loss for rate limits.

If it were me, I think I'd create a dedicated struct that has the shape we want. This will be more developer friendly. In this case, rate limits can either be another struct with properties for each limit, or a dictionary to allow for the handling of new limits without additional driver effort–however rate limiting axes are likely static so I think it's safe to assign them directly to properties.

2024-07-08 17:01 UTC, pnwpedro requested changes
Just naming at this point. I can't remove my StatsCollector -> IStatsCollector comment because it's fixed already.

2024-07-08 17:03 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +        lock (this)
Also, I don't think we need to lock here. If people call this concurrently they might get partial data, but it will be correct.

2024-07-08 17:07 UTC, cynicaljoy commented on Fauna/Client/StatsCollector.cs
> +    public int RateLimitedQueriesByWriteOps;
I think the rate rate limit vars having the same prefix makes it a lot easier to work with.

2024-07-08 17:31 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +    public int RateLimitedQueriesByWriteOps;
Then RateLimitedReadQueryCount, etc etc. The important thing is that we already have QueryCount in this struct, but use *QueriesBy* here.

2024-07-08 17:33 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +        lock (this)
Also here, pretty sure we can remove this lock safely.

2024-07-08 17:53 UTC, pnwpedro requested changes
Last small bit of feedback from me! I thought about these earlier but forgot to include them in the last review.

2024-07-08 17:53 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +    private int _queryTimeMs;
```suggestion
    private long _readOps;
    private long _computeOps;
    private long _writeOps;
    private long _queryTimeMs;
```

2024-07-08 17:53 UTC, pnwpedro commented on Fauna/Client/StatsCollector.cs
> +    private int _storageBytesWrite;
```suggestion
    private long _storageBytesRead;
    private long _storageBytesWrite;
```

2024-07-08 18:07 UTC, pnwpedro approved these changes
LGTM

2024-07-09 16:10 UTC, freels approved these changes
nice. LGTM

2024-07-09 16:10 UTC, freels commented on Fauna/Client/StatsCollector.cs
> +public struct Stats
is it possible to make this readonly?

2024-07-10 12:44 UTC, merged