Add Average LINQ methods
fauna/fauna-dotnet pull request #135
Opened 2024-07-09 20:34 UTC by cynicaljoy

2024-07-10 09:16 UTC, pnwpedro requested changes

2024-07-10 09:16 UTC, pnwpedro commented on Fauna/Linq/QuerySourceDsl.cs
> +            q: QH.MethodCall(mapped, "fold", seed, _avgReducer).Concat(QH.Expr("/")).Concat(QH.MethodCall(QH.Expr("t"), "count")),
I think reuse the `_sumReducer` instead. That will be clearer because `_avgReducer` implies it's producing an average directly.

2024-07-10 14:10 UTC, cynicaljoy commented on Fauna.Test/Linq/Query.Tests.cs
> +        Assert.Throws<InvalidOperationException>(() => db.Author.Where(a => a.Name == "No name").Average(a => a.Age));
not sure exactly what you're asking.

is the exception obvious? we translate it [here](https://github.com/fauna/fauna-dotnet/blob/55c1d8b8dfe5ed54b0919505c6856405e61b3bcf/Fauna/Linq/QuerySourceDsl.cs#L364) -- the message is clear.

is this worth testing here? probably not, I honestly included it because I was curious as to what would happen

2024-07-12 14:05 UTC, pnwpedro commented on Fauna.Test/Linq/Query.Tests.cs
> +        Assert.Throws<InvalidOperationException>(() => db.Author.Where(a => a.Name == "No name").Average(a => a.Age));
i was asking whether or not that specific instance of InvalidOperationException has a sufficiently helpful message. thanks for linking the code.

yes it's worth testing. anytime you test for an exception, we should test the message as well, especially when we throw that exception in many places. it ensures we aren't getting it from an unexpected code path.

2024-07-15 14:58 UTC, pnwpedro approved these changes
🥳

2024-07-15 14:58 UTC, pnwpedro commented on Fauna.Test/Linq/Query.Tests.cs
> +        var avgCastInt = db.Author.Average(a => a.Age);
Weird, I thought the signature wouldn't support this. 🤷

2024-07-15 15:00 UTC, merged