Add Streaming support
fauna/fauna-dotnet pull request #142
Opened 2024-07-19 14:52 UTC by cynicaljoy

### Description

### Motivation and context

### How was the change tested?

### Screenshots (if appropriate):

### Change types

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to Fauna documentation.
- [ ] My change requires a change to the README, and I have updated it accordingly.

2024-08-13 14:41 UTC, pnwpedro requested changes
This is looking really good!

2024-08-13 14:41 UTC, pnwpedro commented on Fauna/Client/Events.cs
> +        }
My gut says we need to build the right exceptions here. Exceptions are built from a QueryFailure right now (see ExceptionFactory), so you'll have to sort that out I think. For example, if a stream results in an abort (is that possible???) we need to expose the data.

2024-08-13 14:41 UTC, pnwpedro commented on Fauna.Test/Integration.Tests.cs
> +    [Test]
Let's add a test that resumes a stream and proves that we didn't miss any items.

2024-08-13 19:42 UTC, cynicaljoy commented on Fauna.Test/Integration.Tests.cs
> +                        Assert.NotNull(evt.Data!.Foo, "Foo should be set");
the first event will be `bar` -- I figured keeping the test simple in this case would be best.

2024-08-13 20:05 UTC, cynicaljoy commented on Fauna/Client/Client.cs
> +            }
the `IOException` ins't thrown until we attempt to read the stream. You can't `yield` inside of a `try` so doing a quick peek on the reader was the simplest way I could solve for making sure we retry when our stream reader goes sideways. I was able to recreate this scenario but restarting the container I was running Fauna in during local dev in the middle of streaming events.

2024-08-13 20:06 UTC, cynicaljoy commented on Fauna/Client/Events.cs
> +        }
yeah I found this a little crufty too but we're trying to solve for both the error and the message within the error being nullable.

2024-08-13 20:15 UTC, findgriffin commented on Fauna/Client/Events.cs
> +public class Event<T> where T : notnull
`Event` seems like a name that could easily get overloaded in a users application, would we better calling this a `FaunaEvent` or `StreamEvent` or <some_other_name>? I haven't looked at what the other drivers do.

2024-08-13 20:15 UTC, findgriffin commented on README.md
> +}
I'd explicitly show an example of what to do with each event here (e.g. print one of the fields).

2024-08-13 20:25 UTC, cynicaljoy commented on Fauna/Client/Events.cs
> +public class Event<T> where T : notnull
We use `Event` in the other drivers (at least I know we do in Go) -- however I've had the same though, so we should come to a consensus on how we want to proceed.

2024-08-13 20:27 UTC, cynicaljoy commented on Fauna/Client/Client.cs
> +            var headers = GetRequestHeaders(finalOptions); // TODO: check this
this TODO was meant to be something I checked before opening the PR 🤦  -- but I'm unsure about if a consumer would need to inject different headers for streaming. Currently they don't have a way to do this.

2024-08-14 10:28 UTC, pnwpedro commented on Fauna.Test/Integration.Tests.cs
> +                        Assert.NotNull(evt.Data!.Foo, "Foo should be set");
Oh right. Let's find a way to assert the values are as expected

2024-08-14 10:30 UTC, pnwpedro commented on Fauna/Client/Client.cs
> +            }
Why though? AFAICT, you should be able to just remove this code without any other changes. If you can't, then what happens if we hit an IOException when we call reader.ReadLineAsync() later?

2024-08-14 10:35 UTC, pnwpedro commented on Fauna/Client/Events.cs
> +public class Event<T> where T : notnull
I was thinking about this with Stream as well. It's a [very common abstract type](https://learn.microsoft.com/en-us/dotnet/api/system.io.stream?view=net-8.0). We use it in this library, for example.

Ideas for both:
1. FaunaEvent and FaunaStream
2. StreamQuery and StreamEvent
3. EventStream and StreamEvent

2024-08-14 10:38 UTC, pnwpedro commented on Fauna/Client/Events.cs
> +        }
Yeah, that's fine. The focus of this comment is around the exception type we're throwing, though. We need to be able to take an error code from an event and create a corresponding exception of the appropriate type.

2024-08-14 10:40 UTC, pnwpedro commented on Fauna/Client/Client.cs
> +            var headers = GetRequestHeaders(finalOptions); // TODO: check this
We should maintain control over this until there's a strong case to expose arbitrary headers that don't correspond to client/stream options.

2024-08-14 10:44 UTC, pnwpedro commented on README.md
> +    Console.WriteLine($"First Name: {person.FirstName} - Last Name: {person.LastName} - Age: {person.Age}");
This is interesting to me because the comment you replaced suggested it was Event<Person>, but in reality it's just Person?

We probably want to show how to deal with exceptions, at least. And is there something missing if users don't get to interact with the events themselves?

2024-08-14 14:33 UTC, cynicaljoy commented on Fauna/Client/Client.cs
> +            }
if I remove this the IOException isn't caught and we don't retry. I'll try to take another pass at this after I address the other items.

2024-08-14 15:02 UTC, cynicaljoy commented on README.md
> +    Console.WriteLine($"First Name: {person.FirstName} - Last Name: {person.LastName} - Age: {person.Age}");
I just messed up the example 😮‍💨  -- I've updated it to show using the evt data.

2024-08-14 16:06 UTC, erickpintor commented
Hey @cynicaljoy! Heads up: there's a small change coming to streaming in the next production release of core. We'll start emitting a per-event cursor that drivers should track instead of the last seen event timestamp in order to reconnect after a crash/network failure. Here's the implementation in Go: https://github.com/fauna/fauna-go/compare/main...stream-cursor

2024-08-14 16:13 UTC, cynicaljoy commented
> Hey @cynicaljoy! Heads up: there's a small change coming to streaming in the next production release of core. We'll start emitting a per-event cursor that drivers should track instead of the last seen event timestamp in order to reconnect after a crash/network failure. Here's the implementation in Go: [fauna/fauna-go@main...stream-cursor](https://github.com/fauna/fauna-go/compare/main...stream-cursor)

chatted with Erick in Slack about this, I cut a card (BT-5048) to track this as we'll end up doing it as a fast-follow since we can't validate against the docker image yet.

2024-08-14 17:25 UTC, pnwpedro commented on Fauna/Client/Events.cs
> +public class Event<T> where T : notnull
Per stand up: EventStream and Event

2024-08-14 17:36 UTC, pnwpedro commented on Fauna/Client/Client.cs
> +            }
per stand up: work IOException into the retry policy directly

2024-08-14 17:37 UTC, pnwpedro commented on Fauna/Client/Events.cs
> +        }
per stand up: cut a follow up task to map error codes to correct exceptions

2024-08-14 17:38 UTC, pnwpedro commented on Fauna.Test/Integration.Tests.cs
> +    [Test]
per stand up: will address with cursor changes coming

2024-08-14 17:58 UTC, cynicaljoy commented on Fauna/Client/Events.cs
> +        }
created BT-5050

2024-08-19 14:58 UTC, pnwpedro requested changes
just a small change 🥳

2024-08-19 15:08 UTC, cynicaljoy commented on Fauna/Client/Events.cs
> +            throw new FaunaException(err.Value);
yup we're tracking this, card BT-5050

2024-08-19 15:13 UTC, cynicaljoy commented on Fauna/Client/Connection.cs
> +                    string? line = await streamReader.ReadLineAsync();
we _should_ be ok since we're calling throw if cancelled at the start of the method, but I went ahead ahead and threw it on.

2024-08-19 15:38 UTC, pnwpedro commented on Fauna/Client/Connection.cs
> +                    string? line = await streamReader.ReadLineAsync().WaitAsync(cancellationToken);
does the direct overload not work here? https://learn.microsoft.com/en-us/dotnet/api/system.io.streamreader.readlineasync?view=net-8.0#system-io-streamreader-readlineasync(system-threading-cancellationtoken)

2024-08-19 15:41 UTC, cynicaljoy commented on Fauna/Client/Connection.cs
> +                    string? line = await streamReader.ReadLineAsync().WaitAsync(cancellationToken);
not available in 6

2024-08-19 15:45 UTC, pnwpedro approved these changes

2024-08-19 16:09 UTC, merged