feat(streams): Use Cursor
fauna/fauna-dotnet pull request #160
Opened 2024-08-26 20:34 UTC by cynicaljoy

### Description

Provide support for the new per-event stream cursor.

### Motivation and context

There's an edge case where resuming a stream from a txn time with lots of documents written could result in event loss. This approach fixes that edge case.

### How was the change tested?

Updated integration test

### Screenshots (if appropriate):

### Change types

* - [x] Bug fix (non-breaking change that fixes an issue)
* - [x] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
* - [ ] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-08-27 15:56 UTC, pnwpedro requested changes

2024-08-27 15:56 UTC, pnwpedro commented on Fauna/Types/Stream.cs
> +        if (LastCursor != null)
I think we should only be writing either the `start_ts` or the `cursor`, but not both. The `cursor` probably takes priority.

2024-09-03 16:15 UTC, adambollen commented on Fauna/Types/Event.cs
> +    public string Cursor { get; private init; } = null!;
I'm not familiar with the `= null!` syntax - what does this do?

2024-09-03 16:51 UTC, cynicaljoy commented on Fauna/Types/Event.cs
> +    public string Cursor { get; private init; } = null!;
Rider suggestion - 

![image](https://github.com/user-attachments/assets/b9275b94-d071-46ef-9acb-02c1bb481e8e)

2024-09-04 09:31 UTC, pnwpedro requested changes
Progress! Let me know if you want to chat about any of these.

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/Core/StreamOptions.cs
> +public class StreamOptions
Let's add more to this class to control for what's allowed instead of the validation in the Client.

1. You can remove { init; }
2. Add constructors that take only the combos allowed, e.g. StreamOptions(token), StreamOptions(token, cursor), StreamOptions(token, startTs)
3. Make the properties readonly

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/IClient.cs
> +        stream.StartTs = streamOptions?.StartTs;
this doesn't seem right. i'd be surprised if we should be setting these in the case where we're issuing a new query.

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/IClient.cs
> +            stream = new Stream(streamOptions.Token!);
there should probably be a constructor that takes token, cursor and start ts in some combination.

also do you need to assert that Token isn't null here? i thought your previous if branch is checking that

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
why are we throwing InvalidOperationException?

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +            throw new Exception($"Missing required field: cursor - {json.ToString()}");
I see we throw Exception elsewhere in this class, but it's too generic.

2024-09-04 09:31 UTC, pnwpedro commented on Fauna/Core/Connection.cs
> +                        listener.Dispatch(null);
afaict, this is essentially calling `listener.Close()`, unless you _must_ enqueue a null event?

2024-09-04 11:11 UTC, cynicaljoy commented on Fauna/Core/Connection.cs
> +                        listener.Dispatch(null);
calling Close wasn't breaking the loop, I had to enqueue something to break on

2024-09-04 11:33 UTC, cynicaljoy commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
> The exception that is thrown when a method call is invalid for the object's current state.

It was an exception type that seemed to make sense to me, open to suggestions.

2024-09-04 11:33 UTC, cynicaljoy commented on Fauna/Types/Event.cs
> +            throw new Exception($"Missing required field: cursor - {json.ToString()}");
how about `InvalidDataException`?

2024-09-04 11:52 UTC, cynicaljoy commented on Fauna/IClient.cs
> +        stream.StartTs = streamOptions?.StartTs;
this is to account for the retry, we already control the conditional use of `Cursor ||  StartTs` in the StreamOptions constructor so we don't need to if-else it here.

2024-09-04 11:58 UTC, cynicaljoy commented on Fauna/IClient.cs
> +        stream.StartTs = streamOptions?.StartTs;
oh I see what you mean now

2024-09-04 12:03 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
Is it conceptually the same as "Missing required field etc etc"?

2024-09-04 12:04 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +            throw new Exception($"Missing required field: cursor - {json.ToString()}");
that seems reasonable

2024-09-04 12:05 UTC, pnwpedro commented on Fauna/Core/Connection.cs
> +                        listener.Dispatch(null);
what about writing a method called BreakAndClose() that does that instead of hiding something inside Dispatch?

2024-09-04 12:30 UTC, cynicaljoy commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
it's more like "Unexpected value"

2024-09-05 14:55 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
what's the unexpected value when elem.Deserialize<string>() coalesces into the throw? like what's actually happening here?

2024-09-05 21:10 UTC, cynicaljoy commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
sycn'd with Adam on this -- we added a message to the exception to clear things up. Using a `throw` here makes the most sense because Deserialize can return null and we need to handle that in rare case that Fauna started returning a `cursor` value that couldn't be deserialized to a string.

2024-09-06 14:08 UTC, pnwpedro commented on Fauna/Types/Event.cs
> +        return elem.Deserialize<string>() ?? throw new InvalidOperationException();
Okay, I think we're getting closer to the why now, which was the original question. It sounds to me like we should just always have a cursor, is that right? So just deserialize and assert it's not null. Their stack trace will point to this line anyway, it's not actionable by the end user. We could throw a protocol exception, but same idea–it's not actionable.

The above assumes when you say "rare case" it's not a rare legitimate case, but something that Fauna should not do.

2024-09-09 13:39 UTC, pnwpedro approved these changes

2024-09-09 15:04 UTC, adambollen approved these changes
\<img src="sheep_emoji.png" /\>

2024-09-09 15:09 UTC, merged