fix(event-streams): CPU Utilization
fauna/fauna-dotnet pull request #176
Opened 2024-09-30 22:45 UTC by cynicaljoy

### Description
Update `OpenStream` to use a `BlockingCollection`

### Motivation and context
We had a tight loop in the `EventListener` that was causing high CPU utilization

### How was the change tested?

Integration tests and

<details>
<summary>Sandbox app</summary>

```csharp
using Fauna;
using Fauna.Mapping;

var client = new Client(Environment.GetEnvironmentVariable("FAUNA_SECRET")!);
var stream = await client.EventStreamAsync<Product>(Query.FQL($"Product.all().toStream()"));
var listenerLoop = Task.Run(async () =>
{
    while (true)
    {
        Console.WriteLine("Waiting for events...");
        await Task.Delay(TimeSpan.FromSeconds(15));
    }
});

var eventsLoop = Task.Run(async () =>
{
    await foreach (var evt in stream)
    {
        Console.WriteLine($"Received Event Type: {evt.Type}");
        if (evt.Data != null)
        {
            Console.WriteLine($"Data: {evt.Data.Name}");
        }
    }
});

await Task.WhenAny(listenerLoop, eventsLoop);

// ReSharper disable once ClassNeverInstantiated.Global
public class Product
{
    [Id] public string? Id { get; set; }
    
    // ReSharper disable once UnassignedField.Global
    public required string Name;
}

```
</details>

### Screenshots (if appropriate):

Before

![image](https://github.com/user-attachments/assets/36cc4864-8c18-44e3-a5d5-5a14e1a2b279)

After

![image](https://github.com/user-attachments/assets/ba387c98-38b9-4d45-ad82-e7fe0dae3680)

### Change types

* - [x] Bug fix (non-breaking change that fixes an issue)
* - [ ] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [x] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
* - [ ] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-09-30 23:19 UTC, jdcryans reviewed
Negative LOC is good :)

2024-09-30 23:19 UTC, jdcryans commented on Fauna.Test/Integration.Tests.cs
> -        Assert.AreEqual("BadRequest: Bad Request", ex?.Message);
How come this changed?

2024-10-01 10:14 UTC, pnwpedro requested changes
🥳

2024-10-01 10:14 UTC, pnwpedro commented on Fauna.Test/Integration.Tests.cs
> -        Assert.AreEqual("BadRequest: Bad Request", ex?.Message);
Yeah, if this is expected I'd like to understand why. We should also rename the test appropriately and assert the correct exception type–hopefully we're not throwing FaunaException anywhere?

2024-10-01 16:37 UTC, cynicaljoy commented on Fauna.Test/Integration.Tests.cs
> -        Assert.AreEqual("BadRequest: Bad Request", ex?.Message);
I wasn't returning the response on failed requests like I was before, but I've put it back to how it was. Initially I thought this was an improvement because we didn't have to create an exception from the response body but I realized it's better to early return as I had it before.

2024-10-01 20:38 UTC, jdcryans approved these changes

2024-10-02 13:31 UTC, pnwpedro approved these changes

2024-10-02 13:31 UTC, merged