feat: Client secret from env var
fauna/fauna-dotnet pull request #178
Opened 2024-10-03 13:12 UTC by cynicaljoy

### Description
Use the `FAUNA_SECRET` env var when initializing the `Client`

### Motivation and context

All other versions of the driver support the `FAUNA_SECRET` env var

### How was the change tested?

Additional tests included

### Screenshots (if appropriate):

### Change types

* - [ ] Bug fix (non-breaking change that fixes an issue)
* - [x] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [x ] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
* - [ ] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-10-03 15:08 UTC, pnwpedro requested changes

2024-10-03 15:08 UTC, pnwpedro commented on Fauna/Configuration.cs
> +    public Configuration(string? secret, HttpClient? httpClient = null)
above, we can do the following, which is more consistent with how we do defaults.
```
    public string Secret { get; init; } = Environment.GetEnvironmentVariable("FAUNA_SECRET") ?? string.Empty;
```

then a separate constructor that excludes string secret?

2024-10-03 18:24 UTC, adambollen commented
Could/should add `FAUNA_ENDPOINT` while we're here, yes?

2024-10-04 14:34 UTC, pnwpedro approved these changes

2024-10-04 14:51 UTC, merged