feat: Event Feeds
fauna/fauna-dotnet pull request #211
Opened 2024-11-04 19:38 UTC by cynicaljoy

### Description

### Motivation and context

### How was the change tested?

### Screenshots (if appropriate):

### Change types

* - [ ] Bug fix (non-breaking change that fixes an issue)
* - [ ] New feature (non-breaking change that adds functionality)
* - [ ] Breaking change (backwards-incompatible fix or feature)

### Checklist:

* - [ ] My code follows the code style of this project.
* - [ ] My change requires a change to Fauna documentation.
* - [ ] My change requires a change to the README, and I have updated it accordingly.

----
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-11-05 18:25 UTC, findgriffin commented
I haven't read your PR closely enough to be sure how this is being handled, but using E2E tests with the JVM driver, there are two kinds of errors we need to handle for event feeds:

The first is where the whole response is an error:

```
Request: 
{"token": "fake_or_incorrect_token"}
Response:
HTTP STATUS: 400, 
{
  "error" : {
    "code" : "invalid_request",
    "message" : "Invalid request body: invalid event source provided."
  }
}
```

The second is where you get a feed page in response, but one of the events is an error:
```
Request: 
{"token": "valid_token", start_ts: 0}
Response:
{
  "events" : [ {
    "type" : "error",
    "error" : {
      "code" : "invalid_stream_start_time",
      "message" : "Stream start time 1970-01-01T00:00:00Z is too far in the past. Recreate the stream and try again."
    },
    "stats" : {
      "read_ops" : 0,
      "storage_bytes_read" : 0,
      "compute_ops" : 0,
      "processing_time_ms" : 0,
      "rate_limits_hit" : [ ]
    }
  } ],
  "cursor" : "gsGCGmcqYs4aOtRswAA=",
  "has_next" : false,
  "stats" : {
    "read_ops" : 0,
    "storage_bytes_read" : 0,
    "compute_ops" : 1,
    "processing_time_ms" : 4,
    "rate_limits_hit" : [ ]
  }
}
```

2024-11-06 15:41 UTC, cynicaljoy commented
@findgriffin do you mock the response or is there a known way to recreate the second scenario (error in events array)?

2024-11-07 06:58 UTC, adambollen reviewed
Just some odds and ends; seems good overall to me.

2024-11-07 06:58 UTC, adambollen commented on Fauna/Client.cs
> +        var finalOptions = QueryOptions.GetFinalQueryOptions(_config.DefaultQueryOptions, null);
Is `GetFinalQueryOptions` needed if no overrides are passed in?  Looks like it'll just return back, so you could save the call.

2024-11-07 06:58 UTC, adambollen commented on Fauna/Core/FeedEnumberable.cs
> +public class FeedPage<T> where T : notnull
Nit: these two classes are definitely big enough to be in their own files (with the filenames matching the class names).

2024-11-07 06:58 UTC, adambollen commented on Fauna.Test/Integration.Tests.cs
> +        Assert.IsEmpty(feed.CurrentPage!.Events, "should note have events");
```suggestion
        Assert.IsEmpty(feed.CurrentPage!.Events, "should not have events");
```

2024-11-07 06:58 UTC, adambollen commented on Fauna/Core/FeedOptions.cs
> +    public FeedOptions(long startTs, int? pageSize = null)
Thoughts on using `DateTime` for `startTs`?  Don't we parse the `ts` as a `DateTime` in this driver?  Seems like a more "idiomatic" thing to do, especially since it's more scrutable what a dev is asking for: "Give me events since this DateTime"

2024-11-07 06:58 UTC, adambollen commented on Fauna/Core/FeedEnumberable.cs
> +    public async Task<bool> NextAsync()
Need to handle `_cancel.IsCancellationRequested` in this method?

2024-11-07 06:58 UTC, adambollen commented on Fauna/Core/FeedEnumberable.cs
> +    /// The last page returned from the Event Feed enumerator.
```suggestion
    /// The latest page returned from the Event Feed enumerator.
```

2024-11-07 10:03 UTC, pnwpedro requested changes
Nice. I caught something that might be a problem in the streams API as well. Let me know if you want to discuss

2024-11-07 10:03 UTC, pnwpedro commented on Fauna/IClient.cs
> +        FeedOptions? feedOptions = null,
Both of these classes have public PageSize, StartTs, and Cursor. How will I know which to set and which will take precedence? I think that's a problem we need to clean up.

EventSource should probably be scoped to just the token, and FeedOptions should have include things like StartTs, Cursor, PageSize.

That might mean you're missing an internal class that passes these things around, or you pass these around instead of collapsing them into EventSource.

2024-11-07 14:03 UTC, cynicaljoy commented on Fauna/Core/FeedEnumberable.cs
> +    public async Task<bool> NextAsync()
I believe we only need to do that in the loops

2024-11-07 14:06 UTC, cynicaljoy commented on Fauna/Core/FeedOptions.cs
> +    public FeedOptions(long startTs, int? pageSize = null)
we used a long for stream options, so if we want to make this change I say we do it in a separate PR

2024-11-07 15:06 UTC, jrodewig commented on Fauna/IClient.cs
> +        }
You can reuse cursors across identical event source queries in the same database. So we could let users pass a cursor with a query for feeds.

Both the JS driver and Python driver let you pass a cursor with a query. For example, in JS, you can do this:

```
const options: FeedClientConfiguration = {
  // Cursor for a previous page
  cursor: "gsGabc456"
};

const feed = client.feed(fql`Product.all().eventSource()`, options);
```

Related JS driver PR here: https://github.com/fauna/fauna-js/pull/298/files

I also confirmed this with @erickpintor here: https://github.com/fauna/fauna-js/pull/301#discussion_r1828490881

2024-11-07 15:06 UTC, jrodewig commented on Fauna.Test/Integration.Tests.cs
> +    }
This should be allowed. I left a comment in the related section below.

2024-11-07 16:42 UTC, jrodewig approved these changes
Narrow + 1 on the cursor/query stuff. Thanks!

2024-11-07 18:57 UTC, erickpintor approved these changes
Can't speak to the driver's internals but, the interface at the client level looks good to me.

2024-11-07 20:28 UTC, pnwpedro approved these changes

2024-11-07 20:39 UTC, cynicaljoy commented on Fauna.Test/Integration.Tests.cs
> +        var ex = Assert.ThrowsAsync<FaunaException>(async () =>
will sort this out in BT-5300

2024-11-07 20:40 UTC, merged